# Logging Properties
logging.threshold.console=trace

#JWT TOKEN CONFIG
security.jwt.secret-key=${JWT_SECRET_KEY}
# expiration time - 30 seconds
security.jwt.expiration-time=30000

#AWS S3 Configuration
cloud.aws.credentials.accessKey=${AWS_ACCESS_KEY}
cloud.aws.credentials.secretKey=${AWS_SECRET_KEY}
cloud.aws.region.static=us-east-1
cloud.aws.s3.bucket=${AWS_S3_BUCKET}

#REST API CONFIG
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
management.endpoints.web.exposure.include: *