ALTER TABLE messages ADD COLUMN reply_to_id BIGINT REFERENCES messages(id) ON DELETE SET NULL;
ALTER TABLE messages ADD COLUMN edited_at   TIMESTAMP;
ALTER TABLE messages ADD COLUMN is_deleted  BOOLEAN NOT NULL DEFAULT FALSE;
