ALTER TABLE accounts ADD COLUMN bio VARCHAR(150);
ALTER TABLE accounts ADD COLUMN measurement_unit VARCHAR(20) DEFAULT 'IMPERIAL';
ALTER TABLE accounts ADD COLUMN currency VARCHAR(10) DEFAULT 'USD';
ALTER TABLE accounts ADD COLUMN is_hidden BOOLEAN DEFAULT FALSE;
